# Generated by Django 4.2.9 on 2024-01-25 11:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cfdi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("tipo_de_comprobante", models.CharField(max_length=1)),
                ("origen", models.CharField(max_length=255)),
                ("serie", models.CharField(blank=True, max_length=30, null=True)),
                ("folio", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "uuid",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=19)),
                ("emisor_rfc", models.CharField(max_length=13)),
                ("emisor", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=150)),
                ("receptor_rfc", models.CharField(max_length=13)),
                ("receptor", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("cancelado", models.IntegerField(blank=True, null=True)),
                (
                    "cancel_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "comentario_cancel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status_code",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "is_cancelable",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("enviado", models.DateTimeField(blank=True, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("comentario", models.CharField(blank=True, max_length=255, null=True)),
                ("version_cfdi", models.CharField(max_length=3)),
                (
                    "uuid_relacionado",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_de_relacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cadena_original",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "create_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "update_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={"db_table": "cfdi", "managed": True,},
        ),
        migrations.CreateModel(
            name="CodigosPostalesMX",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "asentamiento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("codigo", models.CharField(blank=True, max_length=255, null=True)),
                ("colonia", models.CharField(blank=True, max_length=255, null=True)),
                ("municipio", models.CharField(blank=True, max_length=255, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "municipio_sat",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "localidad_sat",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("codigo_sat", models.CharField(blank=True, max_length=255, null=True)),
                ("estado_sat", models.CharField(blank=True, max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={"db_table": "codigos_postales_mx", "managed": True,},
        ),
        migrations.CreateModel(
            name="Comprobante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cfdi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cfdi.cfdi",
                    ),
                ),
            ],
            options={"db_table": "comprobante", "managed": True,},
        ),
        migrations.CreateModel(
            name="FormaPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=5)),
                ("descripcion", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={"db_table": "forma_pago", "managed": True,},
        ),
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=5)),
                ("descripcion", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={"db_table": "metodo_pago", "managed": True,},
        ),
        migrations.CreateModel(
            name="ProductoSat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave_prod_serv", models.CharField(max_length=255, unique=True)),
                ("descripcion", models.CharField(max_length=255)),
                ("similares", models.CharField(max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={"db_table": "producto_sat", "managed": True,},
        ),
        migrations.CreateModel(
            name="RegimenFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=5)),
                ("descripcion", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={"db_table": "regimen_fiscal", "managed": True,},
        ),
        migrations.CreateModel(
            name="TipoComprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=5)),
                ("descripcion", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=50, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={"db_table": "tipo_comprobante", "managed": True,},
        ),
        migrations.CreateModel(
            name="UnidadSat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clave_unidad_sat",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unidad_sat", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nota", models.CharField(blank=True, max_length=255, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={"db_table": "unidad_sat", "managed": True,},
        ),
        migrations.CreateModel(
            name="UsoDeCfdi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=5)),
                ("descripcion", models.CharField(max_length=255)),
                ("persona_fisica", models.BooleanField(default=False)),
                ("persona_moral", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("regimen_fiscal", models.ManyToManyField(to="cfdi.regimenfiscal")),
            ],
            options={"db_table": "uso_cfdi", "managed": True,},
        ),
        migrations.CreateModel(
            name="SubTipoComprobante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=5)),
                ("descripcion", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=50, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "tipo_comprobante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtipos",
                        to="cfdi.tipocomprobante",
                    ),
                ),
            ],
            options={"db_table": "subtipo_comprobante", "managed": True,},
        ),
        migrations.CreateModel(
            name="Contribuyente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "razon_social",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rfc", models.CharField(blank=True, max_length=13, null=True)),
                ("calle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "codigo_postal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("colonia", models.CharField(blank=True, max_length=255, null=True)),
                ("estado", models.CharField(blank=True, max_length=255, null=True)),
                ("municipio", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "numero_exterior",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "numero_interior",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("pais", models.CharField(blank=True, max_length=255, null=True)),
                ("numero_certificado", models.CharField(max_length=255, null=True)),
                (
                    "password_pac",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "password_pfx",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "password_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("certificado_digital", models.BinaryField(blank=True, null=True)),
                ("certificado_digital_pfx", models.BinaryField(blank=True, null=True)),
                ("llave_privada", models.BinaryField(blank=True, null=True)),
                (
                    "certificado_digital_firma",
                    models.BinaryField(blank=True, null=True),
                ),
                ("llave_privada_firma", models.BinaryField(blank=True, null=True)),
                (
                    "password_key_firma",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "encrypted_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timbrado_de_prueba", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "regimen_fiscal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cfdi.regimenfiscal",
                    ),
                ),
            ],
            options={"db_table": "contribuyente", "managed": True,},
        ),
        migrations.CreateModel(
            name="ComprobanteConceptos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "comprobante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cfdi.comprobante",
                    ),
                ),
            ],
            options={"db_table": "comprobante_conceptos", "managed": True,},
        ),
    ]
