# Generated by Django 4.2.9 on 2024-01-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfdi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribuyente",
            name="rfc",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
