# Generated by Django 4.2.9 on 2024-02-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfdi", "0002_alter_contribuyente_rfc"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribuyente",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
