# Generated by Django 4.2.9 on 2024-02-09 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("cfdi", "0003_contribuyente_activo"),
    ]

    operations = [
        
    ]
