# Generated by Django 4.2.9 on 2024-02-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cfdi", "0004_remove_codigospostalesmx_date_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codigospostalesmx", options={"managed": False},
        ),
    ]
