# Generated by Django 4.2.9 on 2024-02-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cfdi", "0005_alter_codigospostalesmx_options"),
    ]

    operations = [
        migrations.DeleteModel(name="CodigosPostalesMX",),
    ]
