# Generated by Django 4.2.9 on 2024-02-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cfdi", "0007_codigospostalesmx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codigospostalesmx", options={"managed": True},
        ),
    ]
