# Generated by Django 4.2.9 on 2024-01-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("descarga_masiva", "0002_descarga"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicituddescarga",
            name="tipo_solicitud",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
