# Generated by Django 4.2.9 on 2024-01-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("descarga_masiva", "0003_solicituddescarga_tipo_solicitud"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodigoRespuestaDescarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=255, null=True)),
                ("mensaje", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={"db_table": "codigo_respuesta_descarga", "managed": True,},
        ),
    ]
