# Generated by Django 4.2.9 on 2024-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("descarga_masiva", "0005_alter_solicituddescarga_fecha_fin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicituddescarga",
            name="importada",
            field=models.BooleanField(default=False),
        ),
    ]
