# Generated by Django 4.2.9 on 2024-02-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codigospostalesmx", options={"managed": True},
        ),
    ]
