# Generated by Django 4.2.9 on 2024-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0002_alter_codigospostalesmx_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="codigospostalesmx", name="date_created",),
        migrations.RemoveField(model_name="codigospostalesmx", name="last_updated",),
        migrations.AddField(
            model_name="codigospostalesmx",
            name="pais",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
