# Generated by Django 4.2.9 on 2024-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0002_alter_codigospostalesmx_options"),
    ]

    operations = [
    ]
