# Generated by Django 4.2.9 on 2024-03-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0003_remove_codigospostalesmx_date_created_and_more"),
    ]

    operations = [
      
    ]
