# Generated by Django 4.2.9 on 2024-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0004_remove_codigospostalesmx_date_created_and_more"),
    ]

    operations = [
    ]
