# Generated by Django 4.2.9 on 2024-02-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion_cfdi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantefiscal",
            name="tipo_de_compribante",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
