# Generated by Django 4.2.9 on 2024-02-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administracion_cfdi", "0002_comprobantefiscal_tipo_de_compribante"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantefiscal",
            name="regimen_fiscal_receptor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="ComprobanteFiscalImpuesto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "impuesto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tipo_factor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tasa_cuota",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "comprobante_fiscal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administracion_cfdi.comprobantefiscal",
                    ),
                ),
            ],
            options={"db_table": "comprobante_fiscal_impuesto", "managed": True,},
        ),
        migrations.CreateModel(
            name="ComprobanteFiscalConcepto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "comprobante_fiscal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administracion_cfdi.comprobantefiscal",
                    ),
                ),
            ],
            options={"db_table": "comprobante_fiscal_concepto", "managed": True,},
        ),
    ]
