# Generated by Django 4.2.9 on 2024-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administracion_cfdi",
            "0003_comprobantefiscal_regimen_fiscal_receptor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comprobantefiscal",
            name="uuid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
