# Generated by Django 4.2.9 on 2024-02-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administracion_cfdi", "0004_alter_comprobantefiscal_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comprobantefiscal",
            old_name="tipo_de_compribante",
            new_name="tipo_de_comprobante",
        ),
    ]
