# Generated by Django 4.2.9 on 2024-02-22 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administracion_cfdi", "0007_comprobantefiscal_contribuyente"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="cantidad",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="clave_prod_serv",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="clave_unidad",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="descripcion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="descuento",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="importe",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="no_identificacion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="objeto_impuesto",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="unidad",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconcepto",
            name="valor_unitario",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="ComprobanteFiscalConceptoImpuesto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "comprobante_fiscal_concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administracion_cfdi.comprobantefiscalconcepto",
                    ),
                ),
            ],
        ),
    ]
