# Generated by Django 4.2.9 on 2024-02-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion_cfdi", "0008_comprobantefiscalconcepto_cantidad_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comprobantefiscalconceptoimpuesto", options={"managed": True},
        ),
        migrations.AddField(
            model_name="comprobantefiscalconceptoimpuesto",
            name="base",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconceptoimpuesto",
            name="importe",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconceptoimpuesto",
            name="impuesto",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconceptoimpuesto",
            name="tasa_cuota",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="comprobantefiscalconceptoimpuesto",
            name="tipo_factor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name="comprobantefiscalconceptoimpuesto",
            table="comprobante_fiscal_concepto_impuesto",
        ),
    ]
