# Generated by Django 4.2.9 on 2024-02-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administracion_cfdi",
            "0009_alter_comprobantefiscalconceptoimpuesto_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantefiscalconceptoimpuesto",
            name="tipo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
