# Generated by Django 4.2.9 on 2024-02-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion_cfdi", "0010_comprobantefiscalconceptoimpuesto_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantefiscal",
            name="total_impuestos_retenidos",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="comprobantefiscal",
            name="total_impuestos_trasladados",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
