# Generated by Django 4.2.9 on 2024-02-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administracion_cfdi",
            "0011_comprobantefiscal_total_impuestos_retenidos_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantefiscalimpuesto",
            name="tipo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
