# Generated by Django 4.2.9 on 2024-03-06 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administracion_cfdi", "0013_alter_comprobantefiscalconcepto_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComprobanteFiscalCancelado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_cancelacion", models.DateTimeField(blank=True, null=True)),
                (
                    "rfc_receptor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nombre_receptor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rfc_emisor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "nombre_emisor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uuid", models.CharField(blank=True, max_length=255, null=True)),
                ("cancelado", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "comprobante_fiscal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administracion_cfdi.comprobantefiscal",
                    ),
                ),
            ],
            options={"db_table": "comprobante_fiscal_cancelado", "managed": True,},
        ),
    ]
