# Generated by Django 4.2.9 on 2024-05-13 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administracion_cfdi", "0014_comprobantefiscalcancelado"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprobantefiscal",
            name="cancelado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comprobantefiscalcancelado",
            name="comprobante_fiscal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comprobante_fiscal_cancelado",
                to="administracion_cfdi.comprobantefiscal",
            ),
        ),
    ]
