# Generated by Django 4.2.9 on 2024-09-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "administracion_cfdi",
            "0016_comprobantefiscalconceptoimpuesto_comprobante_fiscal_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SatComprobanteImpuestos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("receptor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "rfc_receptor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("emisor", models.CharField(blank=True, max_length=255, null=True)),
                ("rfc_emisor", models.CharField(blank=True, max_length=255, null=True)),
                ("fecha", models.DateTimeField(blank=True, null=True)),
                (
                    "uuid",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("serie", models.CharField(blank=True, max_length=255, null=True)),
                ("folio", models.CharField(blank=True, max_length=255, null=True)),
                ("forma_pago", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "metodo_pago",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("uso_cfdi", models.CharField(blank=True, max_length=255, null=True)),
                ("moneda", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tipo_cambio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tipo_de_comprobante",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "iva_trasladado_porc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "iva_trasladado_importe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "iva_retenido_porc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "iva_retenido_importe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "isr_retencion_porc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "isr_retencion_importe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_impuestos_trasladados",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_impuestos_retenidos",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "comprobante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administracion_cfdi.comprobantefiscal",
                    ),
                ),
            ],
            options={"db_table": "sat_comprobante_impuestos", "managed": True,},
        ),
    ]
