# Generated by Django 4.2.9 on 2024-09-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion_cfdi", "0017_satcomprobanteimpuestos"),
    ]

    operations = [
        migrations.AddField(
            model_name="satcomprobanteimpuestos",
            name="fecha_timbrado",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
