# Generated by Django 4.2.9 on 2024-09-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "administracion_cfdi",
            "0019_alter_comprobantefiscalconceptoimpuesto_comprobante_fiscal",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="comprobantefiscalconceptoimpuesto",
            name="comprobante_fiscal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comprobante_fiscal_concepto_impuestos",
                to="administracion_cfdi.comprobantefiscal",
            ),
        ),
        migrations.AlterField(
            model_name="satcomprobanteimpuestos",
            name="comprobante",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
