# Generated by Django 4.2.9 on 2024-09-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administracion_cfdi",
            "0021_rename_isr_retencion_importe_satcomprobanteimpuestos_isr_retenido_importe_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="satcomprobanteimpuestos",
            name="aclaracion_referencia",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="satcomprobanteimpuestos",
            name="fecha_pago",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="satcomprobanteimpuestos",
            name="forma_de_pago",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="satcomprobanteimpuestos",
            name="referencia_pago",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
