# Generated by Django 4.2.9 on 2024-09-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administracion_cfdi",
            "0022_satcomprobanteimpuestos_aclaracion_referencia_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="satcomprobanteimpuestos",
            name="base",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="satcomprobanteimpuestos",
            name="isr_retenido_porc",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="satcomprobanteimpuestos",
            name="iva_retenido_importe",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="satcomprobanteimpuestos",
            name="iva_retenido_porc",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="satcomprobanteimpuestos",
            name="iva_trasladado_porc",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0.0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="satcomprobanteimpuestos",
            name="tipo_cambio",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
    ]
