# Generated by Django 4.2.9 on 2024-09-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion_cfdi", "0023_satcomprobanteimpuestos_base_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="satcomprobanteimpuestos",
            name="sucursal",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="satcomprobanteimpuestos",
            name="tipo_documento",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
