# Generated by Django 4.2.9 on 2024-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administracion_cfdi", "0024_satcomprobanteimpuestos_sucursal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="satcomprobanteimpuestos",
            name="tipo_de_cambio_pago",
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
    ]
